engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      Similar code:
        enabled: false
      import/extensions:
        enabled: false
  file-lines:
    config:
      threshold: 250
  fixme:
    enabled: true
  method-lines:
    config:
      threshold: 50
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- node_modules/
- .nyc_output
- coverage
- template/