language: node_js
addons:
  postgresql: "10.3"
node_js:
  - "8.11.1"
env:
  - NODE_ENV=test
before_script: 
  - psql -c 'create database centermanager_test;' -U postgres
  - npm run migrate 

cache:
  directories:
    - "node_modules"  
script: 
  - npm test
  



language: node_js
node_js:
  - "8.9.0" 
env:
  - NODE_ENV=test                   
before_script:
  - npm install
  - npm install -g codeclimate-test-reporter
  - psql -c 'create database test_db;' -U postgres
  - ./node_modules/.bin/sequelize db:migrate
cache:
  directories:
    - "node_modules"     
script: 
  - npm test  
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  postgresql: "9.6"
  code_climate:
    repo_token:
      secure: 29b82e272b143de5e8d4b448182d4386bb3f8ac609dcd4642014d383