language: node_js
node_js:
  - "8.11.1"
services:
  - postgresql
env:
  - NODE_ENV=test
before_script: 
  - psql -c 'create database centermanager_test;' -U postgres
  - npm run migrate 

cache:
  directories:
    - "node_modules"  
script: 
  - npm test
  
after_script:
  - npm run coverage

